### PR TITLE
Add fontawesome icons to navbar (you need to modify configuration file!)

### PR DESCRIPTION
**Pull request by pepijng**
Please validate my code, i did not manage to add the icon as a parameter in the current configuration so i needed to make an additional section.

### CODE REVIEW

**Comment by pepijng** [comment]
Just a preview
image

**Comment by felix63** [comment]
Looks good!

**Comment by wez3** [comment]
I modified the code to add the icon as a parameter in the current configuration. Now it can be specified after the URI name. Currently the update is on PR for master. it needs to be tested and reviewed. Thanks for this great addition. And for the Apple behaviour as well 👍

**Comment by pepijng** [comment]
Thanks, I see I was close :)

**Comment by pepijng** [comment]
I think you need to modify the example.conf as it does not represent the solution you implemented

**Comment by wez3** [comment]
I've updated the config with:
[navbar]
  [[menu]]
    Dashboard = dashboard, dashboard
    Woonkamer = woonkamer, home
    Slaapkamer = slaapkamer, bed
    Werkkamer = werkkamer, home
    Auto = auto, automobile
    Tuin = tuin, bug
    Verkeer = verkeer, road
    Flitsers = flitsers, camera
    Server = server, desktop
    Instellingen = instellingen, wrench

Do miss something :)?

**Pull request merged**
